services:
  # Discord Bot Service
  - type: web
    name: eleven-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node Shard.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
    autoDeploy: true

  # Website Service  
  - type: web
    name: eleven-website
    env: node
    plan: free
    buildCommand: cd website && npm install
    startCommand: cd website && npm start
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true