services:
  # Discord Bot Service
  - type: web
    name: eleven-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node Shard.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
    autoDeploy: true